#! /bin/sh
# /etc/init.d/future

### BEGIN INIT INFO
# Provides:          future
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

case "$1" in 
    start)
        echo "Starting future booth"
        sudo pigpiod
        cd /home/pi/salone-f3/client
        sudo python future.py &
        ;;
    stop)
        echo "Stopping future"
        killall python
        ;;
    *)
        echo "Usage: /etc/init.d/future start|stop"
        exit 1
        ;;
esac

exit 0

